language: generic 

sudo: required 
services:
  - docker

before_install:
  - docker build -t tanya602/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true tanya602/react-test npm test 

after_success:
   - docker build -t tanys602/multi-client ./client
   - docker build -t tanya602/multi-nginx ./nginx
   - docker build -t tanya602/multi-server ./server
    - docker build -t tanya602/multi-worker ./worker