FROM node:14.14.0-alpine

WORKDIR '/app'

# Copy package.json and package-lock.json (if exists)
COPY ./ package.json ./

RUN npm install

# Copy the rest of the application code
COPY . .

CMD ["npm", "run", "start"]